Delete PrefixFormatterTest in favor of ABSLLogPrefixTest.
abseil/abseil-py pull request #186
Opened 2022-01-26 05:27 UTC by Maxim-38RUS-Zabelin

Reasoning:

1. The PrefixFormatterTest seems to be a piece of some legacy code that somehow lived to our days.
2. Various mocks set up in the `setUp` method are never used anywhere within the test case.
3. The `setUp` method calls to `time.mktime` which is platform-dependent (for more reading refer to https://docs.python.org/3/library/time.html#time.mktime). It is easy to verify running the PrefixFormatterTest under WSL2, where it crashes with `OverflowError: mktime argument out of range`.
4. The only test does not seem to test anything which is related to any prefix formatter.
5. On the other hand, the same test tests implementation details and not an interface by calling to a private function.
6. Deleting the PrefixFormatterTest  does not affect test coverage in any way.

To sum, it seems that the PrefixFormatterTest doesn't add any value, but increases the maintenance burden.

2022-01-26 17:59 UTC, yilei requested changes
Thanks for your contribution and very detailed reasoning! We do have a piece of unreleased test code for the thread_id when integrating with Abseil C++ (and the test case name is indeed due to legacy code), but removing this test case all together here makes sense.

Only one request: could you please kindly squash the two commits? Thanks!

2022-01-27 03:46 UTC, Maxim-38RUS-Zabelin commented
Hi Yilei,

Thank you for a quick reply! With regard to your request for squashing commits, I'm afraid I'm unable to do so because the second commit is a merge commit that cannot participate in squashing. Shall I choose to drop this merge commit, I face another issue: my branch appears to be out-of-date with respect to the upstream/main. So, I'm not sure what's the best way to solve this dilemma; therefore, I would highly appreciate if you could give me a hand with it.

Thank you in advance!

2022-01-27 18:14 UTC, yilei commented
Looking at the state of your fork, you just need to pull upstream with --rebase now.

First make sure you have `upstream` configured:

```
$ git remote -v
origin	https://github.com/Maxim-38RUS-Zabelin/abseil-py (fetch)
origin	https://github.com/Maxim-38RUS-Zabelin/abseil-py (push)
$ git remote add upstream https://github.com/abseil/abseil-py
$ git remote -v
origin	https://github.com/Maxim-38RUS-Zabelin/abseil-py (fetch)
origin	https://github.com/Maxim-38RUS-Zabelin/abseil-py (push)
upstream	https://github.com/abseil/abseil-py (fetch)
upstream	https://github.com/abseil/abseil-py (push)
```

Then in your local repo, you can run this and it should make your clone up to date and your commit at top of the last upstream commit:

```
$ git pull upstream main --rebase
```

Then you can push to your own fork.

2022-01-28 02:52 UTC, Maxim-38RUS-Zabelin commented
Yilei,

Thank you for the detailed answer! I did as you wrote, and it seemed to work.

Please don't hesitate to let me know if anything is not in order. I'd be glad to make necessary changes.

2022-02-02 06:44 UTC, yilei approved these changes
Sorry about the delay, this looks good. Approved. Will wait for the tests to complete before merging.

2022-02-04 21:48 UTC, merged